# Token do MercadoPago para consultar transacoes
token-mp: '<SEU TOKEN DO MERCADO PAGO>'

# Configuracoes do PIX
pix:
  # CPF, CNPJ, Celular com +55 e DDD, email ou aleatoria 
  chave: '<SUA CHAVE PIX>'
  # Nome do beneficiario com ate 25 caracteres
  nome: 'Fulano de Tal'

# Servidor MySQL para salvamento dos dados
mysql:
  db: tests
  host: localhost
  port: 3306
  user: root
  pass: admin

# Tempo de espera para cada acao em segundos
tempos:
  validar: 60
  lista: 30
  criar-pedido: 300
  
# Menu para compra de produtos por PIX
menu:
  titulo: '&9&lCompre produtos por &c&lPIX'
  tamanho: 54
  # Menu para confirmar compra
  confirmar:
    titulo: '&9&lConfirmar compra por &c&lPIX'
    tamanho: 27
    cancelar:
      slot: 19
      icone:
        material: wool
        data: 14
        nome: '&cCancelar'
    confirmar:
      slot: 27
      icone:
        material: wool
        data: 5
        nome: '&aConfirmar'
        descricao:
        - '&7Gerar codigo &bQR &7para'
        - '&7pagar por PIX.'
  # Lista de produtos disponiveis
  produtos:
    VIP1:
      preco: 0.23
      comandos:
      - 'say {player} pagou por PIX!'
      icone:
        slot: 5
        material: diamond_sword
        nome: '&6&lVIP 1 &7- &aR${preco}'
        descricao:
        - '&7Vip por &c30 &7dias'
        - '&7Clique para comprar por &aPIX'

# Livro de ajuda com instrucoes
info:
  titulo: '&aInfo PIX'
  autor: '&bAutoPix'
  paginas:
    1:
    - ' &2&nPagamentos por PIX&r'
    - ' '
    - '&8Para pagar com &cPIX &8 use o comando:'
    - ' '
    - '      &9/comprarpix'
    - ' '
    - '&8Um menu ira aparecer mostrando os produtos disponiveis.'
    2:
    - '&8Escolha o produto que deseja e ao confirmar sera gerado um &8codigo &4&lQR.'
    - ' '
    - '&8Com o app do seu banco scaneie e realize o pagamento.'
    3:
    - '&8Após finalizar obtenha o ID da transacao.'
    - ' '
    - '&8Ele e mostrado no comprovante, tem &c32 &8caracteres e começa com &8a letra &c&lE&8.'
    - ' '
    - '&8Exemplo:'
    - '&7E00416968202301162037NF2oRtQ73bY'
    4:
    - '&8Com o código em maos digite:'
    - ' '
    - ' &9/pix validar <Codigo>'
    - ' '
    - '&8seu PIX sera validado'
    - '&8e voce receberá seu produto.'